name: Refresh Cache

on:
  schedule:
    # runs every 5 minutes
  workflow_dispatch:

jobs:
  refresh_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx httpx-ntlm redis cryptography beautifulsoup4 lxml python-dotenv requests requests_ntlm selectolax Flask flask-cors pycurl

      - name: Run refresh_cache script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: python cache/refresh_cache.py
